name       : haskell-hxt-charproperties
version    : 9.2.0.1
release    : 2
source     :
    - https://hackage.haskell.org/package/hxt-charproperties-9.2.0.1/hxt-charproperties-9.2.0.1.tar.gz : e46614d6bf0390b2a6a1aeeb0771e6d366944da40fb21c12c2f8a94d1f47b4d6
license    : MIT
component  : programming.haskell
summary    : Character proprties defined by XML and Unicode standards
description: |
    Character proprties defined by XML and Unicode standards.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
