name       : haskell-hxt-charproperties
version    : 9.4.0.0
release    : 3
source     :
    - https://hackage.haskell.org/package/hxt-charproperties-9.4.0.0/hxt-charproperties-9.4.0.0.tar.gz : f50ea1d5528025400507f9b181596f7b277e645a1e33ebbc659be22b244468ae
license    : MIT
component  : programming.haskell
summary    : Character proprties defined by XML and Unicode standards
description: |
    Character proprties defined by XML and Unicode standards.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
